# dev 开发环境配置
spring:
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2
      enabled: true
  # 开发环境数据库设置为H2内存数据库
  datasource:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    #    默认URL
    url: jdbc:h2:mem:testdbsa
    driver-class-name: org.h2.Driver
    #    默认用户名
    username: sa
    password: