# 公共属性配置文件
spring:
  profiles:
    active: dev

jasypt:
  encryptor:
    password: VictorHong  #加密的密钥
    algorithm: PBEWithMD5AndDES  #指定解密算法

grpc:
  server:
    port: 9090
    inProcessName: grpc

#spring.application.name: notekeeper-service-grpc
#
#management.endpoints.web.exposure.include: metrics
#management.endpoint.metrics.enabled: true

notion:
  infos:
    # 卡片盒笔记数据库id
    card-box-database-id: ENC(fXZKuIDOOisVJ338ehohA4BT+IlFoAQe71m/IBqI1lj89KHOOgGUZGRdaDA2Pm3uVk+zi/8I7J0=)
    # Jasypt加密，格式为ENC(加密结果)
    token: ENC(YlTaxGKi7irPceIgjOU/tlG/Kk7ZWOdiiYPO19cY2z5HDY20f+lRHUa3x5zZKLDNMa6MLuyKaqfqAh9yuEmmivkw2expDMIFNb5qfbaka0o=)
    # Notion Page 操作URL
    page-url: https://api.notion.com/v1/pages
    # Notion Database 操作URL
    database-url: https://api.notion.com/v1/databases
    # Notion 版本
    version: 2022-06-28

mybatis:
  #  设置Mapper包路径
  type-aliases-package: com.jiahongw.wantee.mapper
  #  mapper-locations: mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30