# dev 开发环境配置
spring:
  h2:
    console:
      settings:
        web-allow-others: true
        trace: true
      path: /h2
      enabled: true
  # 开发环境数据库设置为H2内存数据库
  datasource:
    url: jdbc:h2:mem:testdbsa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
      mode: always