@startmindmap
'https://plantuml.com/mindmap-diagram

caption Thrift类型
'title My super title

* <&flag>Thrift
** 基本类型
*** bool (对应boolean)
*** byte (对应byte)
*** i16 (对应short)
*** i32 (对应int)
*** i64 (对应long)
*** double (对应double)
*** string (对应string)

** 结构体类型
*** struct (在 Java 中是一个 JavaBean)
** 容器类型
*** list (对应ArrayList)
*** set (对应HashSet)
*** map (对应HashMap)
** 异常类型
*** exception (对应Exception)
** 服务类型
*** service 对应服务的类

header
20220127
endheader

center footer create by wujiahong06

@endmindmap
